services:
  postgres:
    image: postgres:latest
    container_name: efms_postgres_db
    restart: on-failure
    environment:
      POSTGRES_USER: techobol
      POSTGRES_PASSWORD: techobol
      POSTGRES_DB: efms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
