spring:
  application:
    name: Employee File Management System BE

  datasource:
    url: jdbc:postgresql://localhost:5432/efms
    username: jodemvel
    password: jodemvel
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect