spring:
  application:
    name: Employee File Management System BE

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/efms}
    username: ${DB_USERNAME:jodemvel}
    password: ${DB_PASSWORD:jodemvel}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:public}

  web:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
      allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
      max-age: ${CORS_MAX_AGE:3600}

efms:
  tenant:
    excluded-paths: ${TENANT_EXCLUDED_PATHS:/swagger-ui,/v3/api-docs,/api/companies}
  pagination:
    max-page-size: ${PAGINATION_MAX_SIZE:100}
    default-size: ${PAGINATION_DEFAULT_SIZE:20}
  general-settings:
    working-days-per-month: ${WORKING_DAYS_PER_MONTH:30}
    seniority-increase-percentage: ${SENIORITY_INCREASE_PERCENTAGE:0.05}
    contribution-afp-percentage: ${CONTRIBUTION_AFP_PERCENTAGE:0.1271}
  scheduler:
    payment:
      process:
        # Runs on the 5th of each month at 23:00
        cron: ${PAYMENT_PROCESS_CRON:0 0 23 14 * ?}
      auto-process: ${PAYMENT_AUTO_PROCESS:true}
      allow-reprocess: ${PAYMENT_ALLOW_REPROCESS:false}

logging:
  level:
    com.efms.employee_file_ms_be: ${LOG_LEVEL_EFMS:DEBUG}

minio:
  url: ${MINIO_ADMIN_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:jodemvel}
  secret-key: ${MINIO_SECRET_KEY:jodemvel}
  bucket: ${MINIO_BUCKET:efms}
  expiry-seconds:  ${MINIO_EXPIRY_SECONDS:3600}