spring:
  application:
    name: Employee File Management System BE

  datasource:
    url: jdbc:postgresql://localhost:5432/efms
    username: jodemvel
    password: jodemvel
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

efms:
  tenant:
    excluded-paths: /swagger-ui,/v3/api-docs,/api/companies
  pagination:
    max-page-size: 100
    default-size: 20
  general-settings:
    working-days-per-month: 30
    seniority-increase-percentage: 0.05
    contribution-afp-percentage: 0.1271

logging:
  level:
    com.efms.employee_file_ms_be: ${LOG_LEVEL_EFMS:DEBUG}